version: '3'
services:
  web:
    container_name: hmg_web_prod
    build: .
    environment:
      RAILS_ENV: production
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
      - ./public:/app/public
      - ./tmp:/app/tmp
      - ./log:/app/log
    ports:
      - "3000:3000"
  
  nginx:
    container_name: hmg_nginx_prod
    build: containers/nginx
    volumes:
      - ./public:/app/public
      - ./tmp:/app/tmp
    ports:
      - 80:80
    depends_on:
      - web
