version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'test'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^ That should look familiar'
      - run:
          name: Running in Unique Container
          command: |
            node -v