version: 2.1
jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers-legacy
    working_directory: ~/hmg
    steps:
      - checkout
      - save_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/hmg
  test:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers-legacy
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'root'
          DB_PASSWORD: ''
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: hmg_test
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: ~/hmg
    steps:
      - checkout
      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "Gemfile.lock" }}
          - v2-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
          - ./vendor/bundle
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      # Database setup
      - run: bundle exec rake db:create --trace
      - run: bundle exec rake db:schema:load --trace
      - run: bundle exec rake db:seed --trace
      # run tests!
      - run:
          name: Run rspec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress --color --format documentation
      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
